spring:
  datasource:
    url: jdbc:mysql://${laven.database.writerendpoint}:${laven.database.port}/${laven.database.name}?useSSL=false
    username: root
    password: password
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  devtools:
    restart:
      additional-paths: src/main/java
laven:
  database:
    writerendpoint: 127.0.0.1
    port: 3306
    name: springboottest

